# Generated by Django 4.2.3 on 2023-07-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "avatar",
                    models.ImageField(upload_to="avatars/", verbose_name="Аватар"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "мужской"), ("female", "женский")],
                        max_length=6,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-mail"
                    ),
                ),
            ],
        ),
    ]
